# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'noteYandexPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'CorePlot', 2.2
  # Pods for noteYandexPractice

  target 'noteYandexPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
